### ISSUE TITLE
Count Modula Matrix Mixer - Incorrect value emitted on patch load

### ISSUE THREAD

**Issue by dpisarcik** [4ms/metamodule-plugin-examples#6] opened 2024-09-05 02:27 UTC
Firmware: v1.0.12
Count Modula Version: 2.5.0  (SDK Version: 1.0)

On preset load, Count Modula Matrix Mixer outputs do not appear to send expected values, despite UI appearing correct.

Expected: On preset load, the display & output of Matrix Mixer 1 (Out 7) is greater than zero. ADSR envelope (Out 1) exhibits ~0.5 - 1s decay.
Actual: On preset load, display is greater than zero.  Output of Matrix Mixer 1 (Out 7) is zero.  ADSR envelope (Out 1) has very short decay.

Reliably reproducing issue when switching between the below two patches.  First patch `srcPanMtx_Test.zip` exhibits the issue.
[srcPanMtx_Test.zip](https://github.com/user-attachments/files/16883000/srcPanMtx_Test.zip)
[srcMixEg_TestC.zip](https://github.com/user-attachments/files/16882999/srcMixEg_TestC.zip)

-----------

`srcPanMtx_Test` takes voltages from a 4ms Source -> 4ms Pan -> Count Modula Matrix Mixer to feed Befaco ADSR decay.  Gate 1 triggers the envelope.  Out 1 outputs the envelope.  Outs 5-8 used to monitor voltages from each stage of the chain.  Out 7 outputs the Matrix Mixer's output.

**Comment by danngreen** [comment] 2024-09-16 19:30
OK, I can confirm this. It looks like channel 1 of the matrix is behaving as if it were in Bipolar mode, but the switch is set to Unipolar. The patch acts normally as soon as you wiggle both the Matrix knobs.

The reason it's doing this is because the MM patch loader first sets all the knobs, and then calls dataFromJson, and then doesn't set any knobs again until something changes. If I have it call dataFromJson before setting the initial knob positions, then it works.

The root cause of this is that VCV sends updates to the params constantly, but that's a performance hit on the MetaModule so we only send updates to params when the value changes. So in this case, the module relies on the parameters being set after the module's json data is loaded from the patch. 

I'll need to test it out a bit to make sure this doesn't break anything else (some built-ins might be relying on the legacy behavior).

**Comment by danngreen** [comment] 2024-09-16 19:39
Ah, I think I spoke too soon. The issue with the values being wrong when loading the patch is fixed, but now there's an issue with the values being always wrong when in Bipolar mode. More work to be done...

**Comment by danngreen** [comment] 2024-09-16 23:02
I have it fixed now, no changes are needed to this repo.
I changed how the MM patch engine initializes modules when adding them to a patch and when loading them from a patch file. In short, the order of `onReset()`, `dataFromJson()`, and setting the param values happens in the right order.

**Closed** 2024-09-16 23:26 UTC
